package view;

import java.time.format.DateTimeFormatter;
import javax.swing.JLabel;
import model.Recipe;

/**
 * This class is used to present the preview of the recipe, in the main window
 * of the app. It is intended, that by clicking on the panel, the user is taken
 * to the main window of the recipe with full information about it
 * @author matija
 */
public class RecipePanel extends javax.swing.JPanel {
    /**
     * Creates new form RecipePanel
     */
    private long recipeId;
    
    public RecipePanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nameLabel = new javax.swing.JLabel();
        ingredientsLabel = new javax.swing.JLabel();
        instructionsLabel = new javax.swing.JLabel();
        dateLabel = new javax.swing.JLabel();
        reviewsLabel = new javax.swing.JLabel();
        appliancesLabel = new javax.swing.JLabel();
        authorLabel = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        setMaximumSize(new java.awt.Dimension(32767, 200));
        setMinimumSize(new java.awt.Dimension(0, 200));
        setPreferredSize(new java.awt.Dimension(1053, 200));

        nameLabel.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        nameLabel.setText("Naziv recepta ");

        ingredientsLabel.setText("Sastojci: sastojak1, sastojak2, sastojak3... ");
        ingredientsLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        instructionsLabel.setText("<html>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent vulputate dapibus dictum. In malesuada orci ipsum, eget sodales felis consectetur eu. In auctor eros est, ut hendrerit velit efficitur ut. Sed molestie diam orci, eu interdum ex tincidunt nec. Nulla nisl lacus sit.</html>");
        instructionsLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        dateLabel.setText("Datum izrade recepta");

        reviewsLabel.setText("Ocena: 1-5");

        appliancesLabel.setText("Kuhinjski aparati: aparat1, aparat2, aparat3...");

        authorLabel.setText("authorLabel");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(dateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(reviewsLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(authorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(appliancesLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1039, Short.MAX_VALUE)
                            .addComponent(instructionsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(ingredientsLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nameLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ingredientsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(appliancesLabel)
                .addGap(13, 13, 13)
                .addComponent(instructionsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(reviewsLabel)
                    .addComponent(dateLabel)
                    .addComponent(authorLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public JLabel getAppliancesLabel() {
        return appliancesLabel;
    }

    public JLabel getDateLabel() {
        return dateLabel;
    }

    public JLabel getIngredientsLabel() {
        return ingredientsLabel;
    }

    public JLabel getInstructionsLabel() {
        return instructionsLabel;
    }

    public JLabel getNameLabel() {
        return nameLabel;
    }

    public JLabel getReviewsLabel() {
        return reviewsLabel;
    }

    public JLabel getAuthorLabel() {
        return authorLabel;
    }

    public long getRecipeId() {
        return recipeId;
    }

    public void setRecipeId(long recipeId) {
        this.recipeId = recipeId;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel appliancesLabel;
    private javax.swing.JLabel authorLabel;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JLabel ingredientsLabel;
    private javax.swing.JLabel instructionsLabel;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel reviewsLabel;
    // End of variables declaration//GEN-END:variables

}
