/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.recipeWindow;

import java.awt.Dimension;
import java.util.ArrayList;

/**
 *
 * @author isido
 */
public class ShowReviews extends javax.swing.JPanel {

    /**
     * Creates new form ShowedRecepies
     * @param ratings
     */
    public ShowReviews(ArrayList<Integer> ratings) {
        initComponents();
        initAllRecipePanels(ratings);
        repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));
    }// </editor-fold>//GEN-END:initComponents

    private void initAllRecipePanels(ArrayList<Integer> ratings) {
        for (int i = 0; i < ratings.size(); i++) {
            ReviewPanel panel = new ReviewPanel(ratings.get(i));
            panel.setPreferredSize(new Dimension(200, 40));
            add(panel);
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
