/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.ingredientPanel;

import java.awt.Color;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import javax.swing.JPanel;

/**
 *
 * @author Jovana
 */
public class LeftPanel extends javax.swing.JPanel {
    private int i=1;
    private GridBagConstraints cbg;
    private final LPanel p;

    /**
     * Creates new form LeftPanel
     */
    public LeftPanel() {
        GridBagLayout gbl = new GridBagLayout();
        this.setLayout(gbl);
        setBackground(Color.red);
        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 102, 0), 1, true));
        cbg = new GridBagConstraints();
        
        cbg.anchor = GridBagConstraints.NORTHWEST;
        cbg.gridx = 0;
        cbg.gridy = 0;
        cbg.fill = GridBagConstraints.HORIZONTAL;
        p = new LPanel();
        this.add(p, cbg);
        
        cbg = new GridBagConstraints();
        cbg.anchor = GridBagConstraints.NORTHWEST;
    }
    
    public void initCategory(JPanel jp){
        cbg.gridy = i;
        this.add(jp, cbg);
        i++;
        p.categories.add(jp);
    }
    
    public void initIngridient(JPanel jp){
        cbg.gridy = i;
        this.add(jp, cbg);
        i++;
        p.ingredients.add(jp);
    }
    
    public void initPanelA(JPanel jp){
        cbg.gridy = 1;
        jp.setVisible(false);
        this.add(jp, cbg);

        p.appliances = jp;
    }
    
    
    
    public void alignment(){
        cbg.weighty=1;
        this.add(new JPanel(),cbg);
    }
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
