/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.CreateRecipeWindow;

import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JFormattedTextField;

/**
 *
 * @author isido
 */
public class IngredientPickerDialog extends javax.swing.JDialog {
    
    private DefaultComboBoxModel<String> ingredientsComboModel;
    private OkIngredientListener okListener;
    boolean editAmount;

    /**
     * Creates new form IngredientPickerDialog
     * @param parent
     * @param modal
     */
    public IngredientPickerDialog(java.awt.Frame parent, boolean modal, boolean edit) {
        super(parent, modal);
        ArrayList<String> ingrs = new ArrayList<>();
        editAmount = edit;
        //{"mleko", "jaja", "brasno", "djumbir", "kisela pavlaka"}
        //ingrs.add("mleko"); ingrs.add("jaja"); ingrs.add("brasno"); ingrs.add("djumbir"); ingrs.add("kisela pavlaka");
        ingredientsComboModel = new DefaultComboBoxModel<>();
        //ingredientsComboModel.addAll(ingrs);
        initComponents();
        
        if (edit){
            ingrComboBox.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        amountFTF = new javax.swing.JFormattedTextField();
        ingrComboBox = new javax.swing.JComboBox<>();
        unitComboBox = new javax.swing.JComboBox<>();
        okButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAutoRequestFocus(false);
        setResizable(false);

        amountFTF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));

        ingrComboBox.setModel(ingredientsComboModel);

        unitComboBox.setEditable(true);
        unitComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "g", "kg", "l", "dl", "ml", "kom" }));

        okButton.setText("Potvrdi");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ingrComboBox, 0, 91, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(amountFTF, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(unitComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(73, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ingrComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(amountFTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(unitComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addComponent(okButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        String ingredient;
        if (!editAmount)
             ingredient = ingredientsComboModel.getSelectedItem().toString();
        else
            ingredient = "";
        Double amount = Double.parseDouble(amountFTF.getText());
        String unit = unitComboBox.getSelectedItem().toString();
        okListener.okIngredientEventEmitted(new OkIngredientEvent(ingredient, amount, unit, editAmount, this));
    }//GEN-LAST:event_okButtonActionPerformed

    public void setOkListener(OkIngredientListener okListener) {
        this.okListener = okListener;
    }

    public DefaultComboBoxModel<String> getIngredientsComboModel() {
        return ingredientsComboModel;
    }

    public void setIngredientsComboModel(DefaultComboBoxModel<String> ingredientsComboModel) {
        this.ingredientsComboModel = ingredientsComboModel;
        this.ingrComboBox.setModel(ingredientsComboModel);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField amountFTF;
    protected javax.swing.JComboBox<String> ingrComboBox;
    private javax.swing.JButton okButton;
    private javax.swing.JComboBox<String> unitComboBox;
    // End of variables declaration//GEN-END:variables

    public JComboBox getIngredientsComboBox() {
        return ingrComboBox;
    }

    public JFormattedTextField getAmountFTF() {
        return amountFTF;
    }

    public JComboBox<String> getUnitComboBox() {
        return unitComboBox;
    }

}
