/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.createUser;

import java.awt.Color;
import java.awt.event.ActionListener;
import java.time.LocalDate;
import java.time.Month;
import java.time.ZoneId;
import java.util.Date;
import java.util.Locale;

/**
 *
 * @author jovandjordjic
 */
public class CreateAccountPanel extends javax.swing.JPanel {

    private ActionListener generatePasswordListener;
    private GenerateUsernameListener generateUserNameListener;
    private CreateAccountListener createAccountListener;

    public void setGeneratePasswordListener(ActionListener generatePasswordListener) {
        this.generatePasswordListener = generatePasswordListener;
    }

    public void setGenerateUserNameListener(GenerateUsernameListener generateUserNameListener) {
        this.generateUserNameListener = generateUserNameListener;
    }

    public void setCreateAccountListener(CreateAccountListener createAccountListener) {
        this.createAccountListener = createAccountListener;
    }

    public void setUsernameTextField(String username) {
        this.userNameTextField.setText(username);
    }

    public void setPasswordTextField(String password) {
        this.passwordTextField.setText(password);
    }

    public void colorTextField(String textField) {
        switch (textField) {
            case "name":
                this.nameTextField.setBackground(Color.red);
                break;
            case "surname":
                this.surnameTextField.setBackground(Color.red);
                break;
            case "email":
                this.emailUserNameTextField.setBackground(Color.red);
                this.emailDomainTextField.setBackground(Color.red);
                this.emailDotComTextField.setBackground(Color.red);
                break;
            case "username":
                this.userNameTextField.setBackground(Color.red);
                break;
            case "password":
                this.passwordTextField.setBackground(Color.red);
                break;
            default:
                break;
        }
    }

    public boolean checkEmailFields() {
        if (emailUserNameTextField.getText().isBlank() || emailDomainTextField.getText().isBlank() || emailDotComTextField.getText().isBlank()) {
            colorTextField("email");
            return false;
        }
        return true;
    }

    /**
     * Creates new form CreateUserPanel
     */
    public CreateAccountPanel() {
        initComponents();
        initializeDateChooser();
    }

    private void initializeDateChooser() {
        this.birthDateChooser.setMaxSelectableDate(Date.from(LocalDate.now().atStartOfDay(ZoneId.systemDefault()).toInstant()));
        this.birthDateChooser.setDate(Date.from(LocalDate.of(1999, Month.MAY, 13).atStartOfDay(ZoneId.systemDefault()).toInstant()));
        this.birthDateChooser.setMinSelectableDate(Date.from(LocalDate.of(1900, Month.JANUARY, 1).atStartOfDay(ZoneId.systemDefault()).toInstant()));

        Locale aLocale = new Locale.Builder().setLanguage("sr").setScript("Latn").setRegion("RS").build();
        this.birthDateChooser.setLocale(aLocale);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelTitleLbl = new javax.swing.JLabel();
        titleSeparator = new javax.swing.JSeparator();
        nameLbl = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        surnameLbl = new javax.swing.JLabel();
        surnameTextField = new javax.swing.JTextField();
        birthDateLbl = new javax.swing.JLabel();
        birthDateChooser = new com.toedter.calendar.JDateChooser();
        emailLbl = new javax.swing.JLabel();
        emailUserNameTextField = new javax.swing.JTextField();
        usernameLbl = new javax.swing.JLabel();
        userNameTextField = new javax.swing.JTextField();
        passwordLbl = new javax.swing.JLabel();
        createAccountBtn = new javax.swing.JButton();
        generateUserNameBtn = new javax.swing.JButton();
        generatePasswordBtn = new javax.swing.JButton();
        atLbl = new javax.swing.JLabel();
        emailDomainTextField = new javax.swing.JTextField();
        dotLbl = new javax.swing.JLabel();
        emailDotComTextField = new javax.swing.JTextField();
        passwordTextField = new javax.swing.JTextField();

        panelTitleLbl.setFont(panelTitleLbl.getFont().deriveFont(panelTitleLbl.getFont().getSize()+12f));
        panelTitleLbl.setText("Registracija");

        nameLbl.setText("Ime:");

        surnameLbl.setText("Prezime:");

        birthDateLbl.setText("Datum rođenja:");

        emailLbl.setText("e-mail adresa:");

        usernameLbl.setText("Korisničko ime:");

        passwordLbl.setText("Lozinka:");

        createAccountBtn.setText("Kreiraj nalog");
        createAccountBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createAccountBtnActionPerformed(evt);
            }
        });

        generateUserNameBtn.setText("Predloži");
        generateUserNameBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateUserNameBtnActionPerformed(evt);
            }
        });

        generatePasswordBtn.setText("Predloži");
        generatePasswordBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generatePasswordBtnActionPerformed(evt);
            }
        });

        atLbl.setText("@");

        dotLbl.setText(".");

        emailDotComTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailDotComTextFieldActionPerformed(evt);
            }
        });

        passwordTextField.setText("jTextField1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titleSeparator)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelTitleLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(surnameLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(surnameTextField))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nameLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nameTextField))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(birthDateLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(birthDateChooser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(createAccountBtn, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(generateUserNameBtn, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(passwordLbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(passwordTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(usernameLbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(userNameTextField)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(generatePasswordBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(emailLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(emailUserNameTextField)
                        .addGap(3, 3, 3)
                        .addComponent(atLbl)
                        .addGap(3, 3, 3)
                        .addComponent(emailDomainTextField)
                        .addGap(5, 5, 5)
                        .addComponent(dotLbl)
                        .addGap(5, 5, 5)
                        .addComponent(emailDotComTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelTitleLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(titleSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLbl)
                    .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(surnameLbl)
                    .addComponent(surnameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(birthDateLbl)
                    .addComponent(birthDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailLbl)
                    .addComponent(emailUserNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(atLbl)
                    .addComponent(emailDomainTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dotLbl)
                    .addComponent(emailDotComTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usernameLbl)
                    .addComponent(userNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(generateUserNameBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordLbl)
                    .addComponent(generatePasswordBtn)
                    .addComponent(passwordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(createAccountBtn)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void generateUserNameBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateUserNameBtnActionPerformed
        if (generateUserNameListener != null) {
            String name = nameTextField.getText();
            String surname = surnameTextField.getText();
            String email = emailUserNameTextField.getText();

            GenerateUsernameEvent ev = new GenerateUsernameEvent(name, surname, email, this);
            generateUserNameListener.generateUsernameEventOccured(ev);
        }
    }//GEN-LAST:event_generateUserNameBtnActionPerformed

    private void generatePasswordBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generatePasswordBtnActionPerformed
        if (generatePasswordListener != null) {
            generatePasswordListener.actionPerformed(evt);
        }
    }//GEN-LAST:event_generatePasswordBtnActionPerformed

    private void createAccountBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createAccountBtnActionPerformed
        if (createAccountListener != null) {
            String name = nameTextField.getText();
            String surname = surnameTextField.getText();
            String username = userNameTextField.getText();
            String password = passwordTextField.getText();
            String email = emailUserNameTextField.getText() + "@" + emailDomainTextField.getText() + "." + emailDotComTextField.getText();

            Date date1 = birthDateChooser.getDate();
            LocalDate birthDate = date1.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();

            CreateAccountEvent ev = new CreateAccountEvent(username, password, name, surname, email, birthDate, this);
            createAccountListener.createNewAccount(ev);
        }
    }//GEN-LAST:event_createAccountBtnActionPerformed

    private void emailDotComTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailDotComTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailDotComTextFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel atLbl;
    private com.toedter.calendar.JDateChooser birthDateChooser;
    private javax.swing.JLabel birthDateLbl;
    private javax.swing.JButton createAccountBtn;
    private javax.swing.JLabel dotLbl;
    private javax.swing.JTextField emailDomainTextField;
    private javax.swing.JTextField emailDotComTextField;
    private javax.swing.JLabel emailLbl;
    private javax.swing.JTextField emailUserNameTextField;
    private javax.swing.JButton generatePasswordBtn;
    private javax.swing.JButton generateUserNameBtn;
    private javax.swing.JLabel nameLbl;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JLabel panelTitleLbl;
    private javax.swing.JLabel passwordLbl;
    private javax.swing.JTextField passwordTextField;
    private javax.swing.JLabel surnameLbl;
    private javax.swing.JTextField surnameTextField;
    private javax.swing.JSeparator titleSeparator;
    private javax.swing.JTextField userNameTextField;
    private javax.swing.JLabel usernameLbl;
    // End of variables declaration//GEN-END:variables
}
